export enum CodeLanguages {
//  ADA = 'ADA',
  BASH = 'BASH',
//  BEFUNGE_93 = 'BEFUNGE_93',
//  BQN = 'BQN',
  BRAINFUCK = 'BRAINFUCK',
////  BRACHYLOG = 'BRACHYLOG',
  C = 'C',
//  C_CLANG = 'C_CLANG',
//  C_OBJECTIVE = 'C_OBJECTIVE',
  C_PLUS_PLUS = 'C_PLUS_PLUS',
//  C_PLUS_PLUS_CLANG = 'C_PLUS_PLUS_CLANG',
//  C_PLUS_PLUS_VC_PLUS_PLUS = 'C_PLUS_PLUS_VC_PLUS_PLUS',
//  C_SHARP = 'C_SHARP',
//  C_VC = 'C_VC',
//  CJAM = 'CJAM',
//  CLOJURE = 'CLOJURE',
////  COBOL = 'COBOL',
  COFFEESCRIPT = 'COFFEESCRIPT',
  COW = 'COW',
//  CRYSTAL = 'CRYSTAL',
  D = 'D',
  DART = 'DART',
  DENO = 'DENO',
//  DRAGON = 'DRAGON',
  ELIXIR = 'ELIXIR',
////  EMACS = 'EMACS',
  EMOJICODE = 'EMOJICODE',
  ERLANG = 'ERLANG',
////  FORTE = 'FORTE',
//  FORTH = 'FORTH',
  FORTRAN = 'FORTRAN',
//  FREEBASIC = 'FREEBASIC',
//  F_SHARP = 'F_SHARP',
//  GAWK = 'GAWK',
  GOJQ = 'GOJQ',
  GOLANG = 'GOLANG',
////  GOLFSCRIPT = 'GOLFSCRIPT',
////  GROOVY = 'GROOVY',
//  HASKELL = 'HASKELL',
//  HAXE = 'HAXE',
//  HUSK = 'HUSK',
//  IVERILOG = 'IVERILOG',
////  JAPT = 'JAPT',
  JAVA = 'JAVA',
////  JELLY = 'JELLY',
//  KOTLIN = 'KOTLIN',
//  LISP = 'LISP',
  LOLCODE = 'LOLCODE',
  LUA = 'LUA',
////  MATLAB = 'MATLAB',
  NASM = 'NASM',
  NASM_64 = 'NASM_64',
  NODE = 'NODE',
//  OCAML = 'OCAML',
//  OCTAVE = 'OCTAVE',
//  ORACLE = 'ORACLE',
//  PASCAL = 'PASCAL',
//  PERL = 'PERL',
  PHP = 'PHP',
//// PONYLANG = 'PONYLANG',
  PROLOG = 'PROLOG',
  PYTHON = 'PYTHON',
  PYTHON_2 = 'PYTHON_2',
//  R = 'R',
  RUBY = 'RUBY',
  RUST = 'RUST',
//  SCALA = 'SCALA',
////  SMALLTALK = 'SMALLTALK',
//  SQLITE_3 = 'SQLITE_3',
  SWIFT = 'SWIFT',
//  TCL = 'TCL',
  TYPESCRIPT = 'TYPESCRIPT',
//  V_LANG = 'V_LANG',
//  VB_NET = 'VB_NET',
//  VYXAL = 'VYXAL',
//  YEETHON = 'YEETHON',
//  ZIG = 'ZIG',
}

export const CodeLanguagesToName = Object.freeze({
//  [CodeLanguages.ADA]: ['ada'],
  [CodeLanguages.BASH]: ['bash', 'sh', 'zsh'],
//  [CodeLanguages.BEFUNGE_93]: ['befunge93'],
//  [CodeLanguages.BQN]: ['bqn'],
  [CodeLanguages.BRAINFUCK]: ['brainfuck', 'bf'],
////  [CodeLanguages.BRACHYLOG]: ['brachylog'],
  [CodeLanguages.C]: ['c', 'c(gcc)', 'h'],
//  [CodeLanguages.C_CLANG]: ['c(clang)'],
//  [CodeLanguages.C_OBJECTIVE]: ['objectivec', 'mm', 'objc', 'obj-c', 'obj-c++', 'objective-c++', 'objective-c', 'oc'],
  [CodeLanguages.C_PLUS_PLUS]: ['c++', 'cpp', 'c++(gcc)', 'h++', 'hpp', 'cxx', 'hxx', 'cc', 'hh'],
//  [CodeLanguages.C_PLUS_PLUS_CLANG]: ['c++(clang)'],
//  [CodeLanguages.C_PLUS_PLUS_VC_PLUS_PLUS]: ['c++(vc++)'],
//  [CodeLanguages.C_SHARP]: ['c#', 'cs', 'csharp'],
//  [CodeLanguages.C_VC]: ['c(vc)'],
//  [CodeLanguages.CJAM]: ['cjam'],
//  [CodeLanguages.CLOJURE]: ['clojure', 'clj'],
////  [CodeLanguages.COBOL]: ['cobol'],
  [CodeLanguages.COFFEESCRIPT]: ['coffeescript', 'coffee', 'cson', 'iced'],
  [CodeLanguages.COW]: ['cow'],
//  [CodeLanguages.CRYSTAL]: ['crystal'],
  [CodeLanguages.D]: ['d'],
  [CodeLanguages.DART]: ['dart'],
  [CodeLanguages.DENO]: ['deno'],
//  [CodeLanguages.DRAGON]: ['dragon'],
  [CodeLanguages.ELIXIR]: ['elixir', 'ex'],
////  [CodeLanguages.EMACS]: ['emacs'],
  [CodeLanguages.EMOJICODE]: ['emojicode', 'emoji'],
  [CodeLanguages.ERLANG]: ['erlang', 'erl'],
//  [CodeLanguages.F_SHARP]: ['f#', 'fs', 'fsharp'],
////  [CodeLanguages.FORTE]: ['forte'],
//  [CodeLanguages.FORTH]: ['forth'],
  [CodeLanguages.FORTRAN]: ['fortran', 'fort', 'f90', 'f95'],
//  [CodeLanguages.FREEBASIC]: ['freebasic'],
//  [CodeLanguages.GAWK]: ['gawk'],
  [CodeLanguages.GOJQ]: ['gojq'],
  [CodeLanguages.GOLANG]: ['go', 'golang'],
////  [CodeLanguages.GOLFSCRIPT]: ['golfscript', 'golf'],
////  [CodeLanguages.GROOVY]: ['groovy'],
//  [CodeLanguages.HASKELL]: ['haskell', 'hs'],
//  [CodeLanguages.HAXE]: ['haxe', 'hx'],
//  [CodeLanguages.HUSK]: ['husk'],
//  [CodeLanguages.IVERILOG]: ['iverilog'],
////  [CodeLanguages.JAPT]: ['japt'],
  [CodeLanguages.JAVA]: ['java', 'jsp'],
////  [CodeLanguages.JELLY]: ['jelly'],
//  [CodeLanguages.KOTLIN]: ['kotlin', 'kot', 'kt'],
//  [CodeLanguages.LISP]: ['commonlisp', 'lisp'],
  [CodeLanguages.LOLCODE]: ['lolcode', 'lol'],
  [CodeLanguages.LUA]: ['lua'],
//  [CodeLanguages.MATLAB]: ['matlab', 'matl'],
//  [CodeLanguages.MYSQL]: ['mysql'],
  [CodeLanguages.NASM]: ['nasm', 'nasm32', 'asm', 'assembly'],
  [CodeLanguages.NASM_64]: ['nasm64', 'asm64', 'assembly64'],
  [CodeLanguages.NODE]: ['javascript', 'js', 'node.js', 'node', 'jsx'],
//  [CodeLanguages.OCAML]: ['ocaml', 'ml'],
//  [CodeLanguages.OCTAVE]: ['octave'],
//  [CodeLanguages.ORACLE]: ['oracle'],
//  [CodeLanguages.PASCAL]: ['pascal'],
//  [CodeLanguages.PERL]: ['perl', 'pl', 'pm'],
  [CodeLanguages.PHP]: ['php'],
////  [CodeLanguages.PONYLANG]: ['pony'],
////  [CodeLanguages.POSTGRES_SQL]: ['postgresql', 'psql', 'postgres'],
  [CodeLanguages.PROLOG]: ['prolog', 'pro'],
  [CodeLanguages.PYTHON]: ['python', 'python3', 'py', 'py3'],
  [CodeLanguages.PYTHON_2]: ['python2', 'python2.7', 'py2.7', 'py2'],
//  [CodeLanguages.R]: ['r'],
  [CodeLanguages.RUBY]: ['ruby', 'rb'],
  [CodeLanguages.RUST]: ['rust', 'rs'],
//  [CodeLanguages.SCALA]: ['scala'],
////  [CodeLanguages.SCHEME]: ['scheme'],
////  [CodeLanguages.SMALLTALK]: ['smalltalk'],
////  [CodeLanguages.SQL_SERVER]: ['sqlserver'],
//  [CodeLanguages.SQLITE_3]: ['sqlite3'],
  [CodeLanguages.SWIFT]: ['swift'],
//  [CodeLanguages.TCL]: ['tcl', 'tk'],
  [CodeLanguages.TYPESCRIPT]: ['typescript', 'ts'],
//  [CodeLanguages.V_LANG]: ['vlang'],
//  [CodeLanguages.VB_NET]: ['vbnet', 'visualbasic', 'vb'],
//  [CodeLanguages.VYXAL]: ['vyxal'],
//  [CodeLanguages.YEETHON]: ['yeethon'],
//  [CodeLanguages.ZIG]: ['zig'],
});